### PR TITLE
Docker convenience execution script

### PR DESCRIPTION
**Pull request by Doomsdayrs**
Here is a simple script to allow anyone to build easily, in my response to https://github.com/AsteroidOS/asteroid/issues/141

### CODE REVIEW

**Comment by jrtberlin** [comment]
Thank you for your contribution. I'm all in for more convenience.
That said, there are two minor changes I would like to see.

1.  Docker should not be installed by curl-ing a random file on the internet and executing it with root.

    One of the big advantages of Linux are package managers and they do generally a good job installing packages and their dependencies. I think the script should just exit with an error and tell the user that docker is missing. (If you really want to you could check `/etc/os-release` and use the package manager directly. Keep in mind that os-release might not be there (e.g. MacOS)!)

2. Replace the backticks with `$(...)`

    This is not a mistake, just something that would be nice since backticks [are considered legacy](http://mywiki.wooledge.org/BashFAQ/082). This shouldn't be an issue but the rest of the command uses `$(...)` so it's more a consistency thing.  (We should change that on our own documentation as well)

    I would replace in [line 39](https://github.com/AsteroidOS/asteroid/blob/559d1d7e7cee8adcb2931409a1774c5643b8d119/executeDocker.sh#L39)
    ``` 
    -u `id -u`:`id -g`
    ```
    with something like:
    ```
    -u "$(id -u):$(id -g)"
    ```

**Comment by FlorentRevest** [comment]
Lines 27, 33 and 39 are the only useful commands only wrapped with lots of syntax.
I would prefer if these were somehow integrated to the existing infra instead of providing wrappers on top of wrappers and new cli tools to learn.
For example, maybe we could have a docker argument in prepare-build.sh. Something like "prepare-build.sh docker bass" that would spin up a container prepared for a bass build and start a remote shell in there so that users could just follow the usual instructions. They could run bitbake asteroid-image, or modifications to src/ etc...

**Comment by Doomsdayrs** [comment]
> Thank you for your contribution. I'm all in for more convenience.
> That said, there are two minor changes I would like to see.
> 
>     1. Docker should not be installed by curl-ing a random file on the internet and executing it with root.
>        One of the big advantages of Linux are package managers and they do generally a good job installing packages and their dependencies. I think the script should just exit with an error and tell the user that docker is missing. (If you really want to you could check `/etc/os-release` and use the package manager directly. Keep in mind that os-release might not be there (e.g. MacOS)!)
https://get.docker.com is listed as a way to install docker, from Dockers official installation guide. But good point, I'll just print out a request to just install docker

>     2. Replace the backticks with `$(...)`
>        This is not a mistake, just something that would be nice since backticks [are considered legacy](http://mywiki.wooledge.org/BashFAQ/082). This shouldn't be an issue but the rest of the command uses `$(...)` so it's more a consistency thing.  (We should change that on our own documentation as well)
>        I would replace in [line 39](https://github.com/AsteroidOS/asteroid/blob/559d1d7e7cee8adcb2931409a1774c5643b8d119/executeDocker.sh#L39)
>        ```
>        -u `id -u`:`id -g`
>        ```
>        
>        
>        with something like:
>        ```
>        -u "$(id -u):$(id -g)"
>        ```
Done, This should also be updated on the website as I took the line from it https://asteroidos.org/wiki/building-asteroidos/

**Comment by Doomsdayrs** [comment]
@FlorentRevest 
> I would prefer if these were somehow integrated to the existing infra instead of providing wrappers on top of wrappers and new cli tools to learn.
It's has 4 commands, it shrinks down all need for the documentation for docker building, and its purpose is defined. 

> For example, maybe we could have a docker argument in prepare-build.sh. Something like "prepare-build.sh docker bass" that would spin up a container prepared for a bass build and start a remote shell in there so that users could just follow the usual instructions. They could run bitbake asteroid-image, or modifications to src/ etc...
prepare-build.sh should remain the script to prepare a build, Nothing more, Leave the scripts defined to their purpose, sweet and simple scripts. 

I'll simplify the command line ever more for you

**Comment by Doomsdayrs** [comment]
@FlorentRevest Even simpler, Just for you~

**Comment by Doomsdayrs** [comment]
Well. That was not what I wanted..

**Comment by beroset** [comment]
I don't know if it helps, but both `docker` and `podman` have the ability to create an image from the URL of a github repository.  So without having downloaded anything from the Asteroid project one can issue this command to build an image:

```
docker build -t asteroidos-buildtools https://github.com/AsteroidOS/asteroid.git
```

**Pull request closed without merging**
