### PR TITLE
Add Skipjack pointing to Release Repo

### PR DESCRIPTION
**Pull request by R0NAM1**
Allow skipjack to be built with the prepare script, pointing towards AsteroidOS's repo's.

### CODE REVIEW

**Comment by MagneFire** [comment]
This should also bring support for the non-plus variant: https://github.com/AsteroidOS/asteroid/issues/106.

**Comment by R0NAM1** [comment]
Hopefully, just need to remove that one patch (0004-skipjack-ddr-add-dts-support-for-1GB-DDR.patch), correct?

**Comment by MagneFire** [comment]
I don't think that is needed, that patch adds support for multiple variants (presumably the old variant is the non-plus).

**Comment by R0NAM1** [comment]
It is, that's nice.

**Pull request merged**
